// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbeqilfjwikqnzyhckew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRiZXFpbGZqd2lrcW56eWhja2V3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNTI5NjgsImV4cCI6MjA2OTcyODk2OH0.5T_Ho90W0yOTgRrs-4FMl8Z9iYtf0j3IDAVNgbtiAwk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});